@extends('layouts.app')
@section('title', 'Monthly Reports')
@section('page-title', 'Monthly Reports')
@section('page-subtitle', 'Generate and view attendance reports')

@section('content')
<div class="space-y-6">

  {{-- Generate Report Form --}}
  <div class="bg-white/5 border border-white/10 rounded-2xl p-6">
    <h2 class="text-white font-semibold mb-5">Generate New Report</h2>
    <form method="POST" action="{{ route('reports.generate') }}"
          class="flex flex-wrap items-end gap-4">
      @csrf

      {{-- Month --}}
      <div>
        <label class="block text-white/50 text-xs uppercase tracking-wider mb-1.5">Month</label>
        <select name="month"
                class="bg-white/5 border border-white/10 rounded-xl px-4 py-2.5
                       text-white text-sm focus:outline-none focus:ring-2 focus:ring-[#4CAF82]">
          @for($m = 1; $m <= 12; $m++)
            <option value="{{ $m }}" {{ $m == $currentMonth ? 'selected' : '' }}>
              {{ Carbon\Carbon::create(null, $m)->format('F') }}
            </option>
          @endfor
        </select>
      </div>

      {{-- Year --}}
      <div>
        <label class="block text-white/50 text-xs uppercase tracking-wider mb-1.5">Year</label>
        <select name="year"
                class="bg-white/5 border border-white/10 rounded-xl px-4 py-2.5
                       text-white text-sm focus:outline-none focus:ring-2 focus:ring-[#4CAF82]">
          @for($y = now()->year; $y >= 2024; $y--)
            <option value="{{ $y }}" {{ $y == $currentYear ? 'selected' : '' }}>
              {{ $y }}
            </option>
          @endfor
        </select>
      </div>

      {{-- Department --}}
      <div>
        <label class="block text-white/50 text-xs uppercase tracking-wider mb-1.5">Department</label>
        <select name="department"
                class="bg-white/5 border border-white/10 rounded-xl px-4 py-2.5
                       text-white text-sm focus:outline-none focus:ring-2 focus:ring-[#4CAF82]">
          <option value="">All Departments</option>
          @foreach($departments as $dept)
            <option value="{{ $dept }}">{{ $dept }}</option>
          @endforeach
        </select>
      </div>

      {{-- Submit --}}
      <button type="submit"
              class="bg-[#4CAF82] hover:bg-[#3d9e71] text-white font-semibold
                     px-6 py-2.5 rounded-xl text-sm transition-colors flex items-center gap-2">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round"
                d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125
                   1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0
                   12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125
                   1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621
                   0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"/>
        </svg>
        Generate Report
      </button>
    </form>
  </div>

  {{-- Generated Reports List --}}
  <div class="bg-white/5 border border-white/10 rounded-2xl overflow-hidden">
    <div class="px-6 py-4 border-b border-white/10">
      <h2 class="text-white font-semibold">Generated Reports</h2>
    </div>
    <table class="w-full">
      <thead>
        <tr class="border-b border-white/10 bg-white/3">
          <th class="text-left px-6 py-4 text-xs font-semibold text-white/50 uppercase tracking-wider">Period</th>
          <th class="text-left px-6 py-4 text-xs font-semibold text-white/50 uppercase tracking-wider">Department</th>
          <th class="text-left px-6 py-4 text-xs font-semibold text-white/50 uppercase tracking-wider">Generated By</th>
          <th class="text-left px-6 py-4 text-xs font-semibold text-white/50 uppercase tracking-wider">Generated At</th>
          <th class="text-right px-6 py-4 text-xs font-semibold text-white/50 uppercase tracking-wider">Actions</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-white/5">
        @forelse($reports as $report)
          <tr class="hover:bg-white/3 transition-colors">
            <td class="px-6 py-4">
              <p class="text-white text-sm font-semibold">
                {{ Carbon\Carbon::create($report->year, $report->month)->format('F Y') }}
              </p>
            </td>
            <td class="px-6 py-4">
              <span class="text-white/60 text-sm">{{ $report->department }}</span>
            </td>
            <td class="px-6 py-4">
              <span class="text-white/60 text-sm">{{ $report->generatedBy?->full_name ?? 'N/A' }}</span>
            </td>
            <td class="px-6 py-4">
              <span class="text-white/60 text-sm">
                {{ \Carbon\Carbon::parse($report->generated_at)->format('M d, Y h:i A') }}
              </span>
            </td>
            <td class="px-6 py-4">
              <div class="flex items-center justify-end gap-3">
                <a href="{{ route('reports.download', $report) }}"
                   class="text-[#4CAF82] hover:underline text-sm font-medium">
                  View →
                </a>
                <form method="POST" action="{{ route('reports.destroy', $report) }}"
                      onsubmit="return confirm('Delete this report?')">
                  @csrf @method('DELETE')
                  <button type="submit" class="text-red-400 hover:underline text-sm">Delete</button>
                </form>
              </div>
            </td>
          </tr>
        @empty
          <tr>
            <td colspan="5" class="px-6 py-12 text-center text-white/30 text-sm">
              No reports generated yet.
            </td>
          </tr>
        @endforelse
      </tbody>
    </table>
    @if($reports->hasPages())
      <div class="px-6 py-4 border-t border-white/10">{{ $reports->links() }}</div>
    @endif
  </div>
</div>
@endsection
