<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 20px; }
        body { font-family: Helvetica, Arial, sans-serif; color: #1a1a1a; font-size: 10px; }
        h1 { font-size: 16px; margin-bottom: 2px; }
        h2 { font-size: 11px; margin: 14px 0 4px; color: #0a2018; }
        .subtitle { color: #666; font-size: 10px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #0a2018; color: #ffffff; text-align: left; padding: 6px 8px; font-size: 9px; text-transform: uppercase; }
        td { padding: 5px 8px; border-bottom: 1px solid #ddd; font-size: 9.5px; }
        tr:nth-child(even) td { background: #f7f7f7; }
        .center { text-align: center; }
        .footer { margin-top: 16px; font-size: 8px; color: #888; }
        .daily-section { margin-top: 10px; page-break-inside: avoid; }
        .daily-table th { background: #444; font-size: 8.5px; }
        .daily-table td { font-size: 8.5px; padding: 4px 8px; }
        .late-row td { background: #fdecea !important; color: #b91c1c; }
        .page-break { page-break-before: always; }
    </style>
</head>
<body>
    <h1>SmartGate ACC - Monthly Attendance Report</h1>
    <p class="subtitle">
        {{ $monthName }} &middot; {{ $report->department }} &middot;
        Generated by {{ $report->generatedBy->full_name ?? "N/A" }} on {{ $report->generated_at->format("M d, Y g:i A") }}
    </p>

    <table>
        <thead>
            <tr>
                <th>Code</th><th>Name</th><th>Position</th><th>Department</th><th>Type</th>
                <th class="center">Days Present</th><th class="center">Lates</th>
                <th class="center">Morning In</th><th class="center">Morning Out</th>
                <th class="center">Afternoon In</th><th class="center">Afternoon Out</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reportData as $row)
            <tr>
                <td>{{ $row["employee_code"] }}</td>
                <td>{{ $row["name"] }}</td>
                <td>{{ $row["position"] }}</td>
                <td>{{ $row["department"] }}</td>
                <td>{{ ucfirst($row["employment_type"]) }}</td>
                <td class="center">{{ $row["days_present"] }}</td>
                <td class="center">{{ $row["lates"] }}</td>
                <td class="center">{{ $row["morning_in"] }}</td>
                <td class="center">{{ $row["morning_out"] }}</td>
                <td class="center">{{ $row["afternoon_in"] }}</td>
                <td class="center">{{ $row["afternoon_out"] }}</td>
            </tr>
            @empty
            <tr><td colspan="11" class="center">No records found for this period.</td></tr>
            @endforelse
        </tbody>
    </table>

    @if(count($reportData) > 0)
        <div class="page-break"></div>
        <h1 style="font-size: 13px;">Daily Scan Times per Employee</h1>
        <p class="subtitle">{{ $monthName }} &middot; {{ $report->department }}</p>

        @foreach($reportData as $row)
            <div class="daily-section">
                <h2>{{ $row["name"] }} ({{ $row["employee_code"] }})</h2>
                <table class="daily-table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th class="center">AM In</th>
                            <th class="center">AM Out</th>
                            <th class="center">PM In</th>
                            <th class="center">PM Out</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($row["daily_logs"] as $day)
                        <tr class="{{ $day['is_late'] ? 'late-row' : '' }}">
                            <td>{{ $day["date"] }}</td>
                            <td class="center">{{ $day["morning_in"] }}</td>
                            <td class="center">{{ $day["morning_out"] }}</td>
                            <td class="center">{{ $day["afternoon_in"] }}</td>
                            <td class="center">{{ $day["afternoon_out"] }}</td>
                        </tr>
                        @empty
                        <tr><td colspan="5" class="center">No scan records this month.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        @endforeach
    @endif

    <p class="footer">Generated by SmartGate ACC Admin Dashboard - {{ now()->format("M d, Y g:i A") }}</p>
</body>
</html>