@extends('layouts.app')
@section('title', 'Monthly Report â€” ' . $monthName)
@section('page-title', 'Monthly Attendance Report')
@section('page-subtitle', $monthName . ' Â· ' . $report->department)

@section('content')
<div class="space-y-4">

  {{-- Report Header --}}
  <div class="bg-white/5 border border-white/10 rounded-2xl p-6">
    <div class="flex items-center justify-between">
      <div>
        <p class="text-white/50 text-xs uppercase tracking-wider">Report Period</p>
        <p class="text-white text-2xl font-bold mt-1">{{ $monthName }}</p>
        <p class="text-white/40 text-sm mt-0.5">{{ $report->department }}</p>
      </div>
      <div class="text-right">
        <p class="text-white/50 text-xs uppercase tracking-wider">Generated By</p>
        <p class="text-white text-sm mt-1">{{ $report->generatedBy?->full_name }}</p>
        <p class="text-white/40 text-xs mt-0.5">
          {{ \Carbon\Carbon::parse($report->generated_at)->format('M d, Y h:i A') }}
        </p>
      </div>
      <div class="flex items-center gap-3">
        <a href="{{ route('reports.export-pdf', $report) }}"
           class="bg-white/5 hover:bg-white/10 text-white/70 border border-white/10
                  font-medium px-5 py-2.5 rounded-xl text-sm transition-colors flex items-center gap-2">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"/>
          </svg>
          Export PDF
        </a>
        <a href="{{ route('reports.export-csv', $report) }}"
           class="bg-white/5 hover:bg-white/10 text-white/70 border border-white/10
                  font-medium px-5 py-2.5 rounded-xl text-sm transition-colors flex items-center gap-2">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"/>
          </svg>
          Export CSV
        </a>
        <button onclick="window.print()"
                class="bg-[#4CAF82] hover:bg-[#3d9e71] text-white font-semibold
                       px-5 py-2.5 rounded-xl text-sm transition-colors flex items-center gap-2">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round"
                  d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415
                     0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66
                     18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662
                     0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0
                     0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055
                     0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768
                     -2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5
                     0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125
                     -1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18
                     10.5h.008v.008H18V10.5zm-3 0h.008v.008H15V10.5z"/>
          </svg>
          Print
        </button>
        <a href="{{ route('reports.index') }}"
           class="bg-white/5 hover:bg-white/10 text-white/60 border border-white/10
                  font-medium px-5 py-2.5 rounded-xl text-sm transition-colors">
          â† Back
        </a>
      </div>
    </div>
  </div>

  {{-- Summary Stats --}}
  @php
    $totalEmployees = count($reportData);
    $totalPresent   = collect($reportData)->sum('days_present');
    $totalLates     = collect($reportData)->sum('lates');
  @endphp
  <div class="grid grid-cols-3 gap-4">
    <div class="bg-white/5 border border-white/10 rounded-2xl p-5">
      <p class="text-white/50 text-xs uppercase tracking-wider mb-2">Total Employees</p>
      <p class="text-3xl font-bold text-white">{{ $totalEmployees }}</p>
    </div>
    <div class="bg-[#4CAF82]/5 border border-[#4CAF82]/20 rounded-2xl p-5">
      <p class="text-[#4CAF82] text-xs uppercase tracking-wider mb-2">Total Days Present</p>
      <p class="text-3xl font-bold text-white">{{ $totalPresent }}</p>
    </div>
    <div class="bg-red-500/5 border border-red-500/20 rounded-2xl p-5">
      <p class="text-red-400 text-xs uppercase tracking-wider mb-2">Total Lates</p>
      <p class="text-3xl font-bold text-white">{{ $totalLates }}</p>
    </div>
  </div>

  {{-- Report Table --}}
  <div class="bg-white/5 border border-white/10 rounded-2xl overflow-hidden">
    <table class="w-full text-sm">
      <thead>
        <tr class="border-b border-white/10 bg-white/3">
          <th class="text-left px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">#</th>
          <th class="text-left px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">Name</th>
          <th class="text-left px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">Code</th>
          <th class="text-left px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">Position</th>
          <th class="text-left px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">Type</th>
          <th class="text-center px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">AM In</th>
          <th class="text-center px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">AM Out</th>
          <th class="text-center px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">PM In</th>
          <th class="text-center px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">PM Out</th>
          <th class="text-center px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider">Days Present</th>
          <th class="text-center px-4 py-3 text-xs font-semibold text-red-400 uppercase tracking-wider">Lates</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-white/5">
        @forelse($reportData as $i => $row)
          <tr class="hover:bg-white/3 transition-colors cursor-pointer"
              onclick="document.getElementById('daily-{{ $i }}').classList.toggle('hidden')">
            <td class="px-4 py-3 text-white/30">{{ $i + 1 }}</td>
            <td class="px-4 py-3 text-white font-medium flex items-center gap-2">
              <svg class="w-3.5 h-3.5 text-white/40" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5"/>
              </svg>
              {{ $row['name'] }}
            </td>
            <td class="px-4 py-3 text-white/50 font-mono text-xs">{{ $row['employee_code'] }}</td>
            <td class="px-4 py-3 text-white/60">{{ $row['position'] }}</td>
            <td class="px-4 py-3">
              <span class="text-xs px-2 py-0.5 rounded-full
                           {{ $row['employment_type'] === 'faculty'
                              ? 'bg-blue-500/15 text-blue-400'
                              : 'bg-purple-500/15 text-purple-400' }}">
                {{ ucfirst($row['employment_type']) }}
              </span>
            </td>
            <td class="px-4 py-3 text-center text-white">{{ $row['morning_in'] }}</td>
            <td class="px-4 py-3 text-center text-white/60">{{ $row['morning_out'] }}</td>
            <td class="px-4 py-3 text-center text-white">{{ $row['afternoon_in'] }}</td>
            <td class="px-4 py-3 text-center text-white/60">{{ $row['afternoon_out'] }}</td>
            <td class="px-4 py-3 text-center">
              <span class="text-[#4CAF82] font-bold">{{ $row['days_present'] }}</span>
            </td>
            <td class="px-4 py-3 text-center">
              @if($row['lates'] > 0)
                <span class="text-red-400 font-bold">{{ $row['lates'] }}</span>
              @else
                <span class="text-white/30">0</span>
              @endif
            </td>
          </tr>

          <tr id="daily-{{ $i }}" class="hidden">
            <td colspan="11" class="px-4 py-4 bg-black/20">
              <p class="text-white/40 text-xs uppercase tracking-wider mb-3">
                Daily Scan Times - {{ $row['name'] }}
              </p>
              <div class="overflow-x-auto rounded-xl border border-white/10">
                <table class="w-full text-xs">
                  <thead>
                    <tr class="border-b border-white/10 bg-white/5">
                      <th class="text-left px-3 py-2 text-white/40 uppercase tracking-wider">Date</th>
                      <th class="text-center px-3 py-2 text-white/40 uppercase tracking-wider">AM In</th>
                      <th class="text-center px-3 py-2 text-white/40 uppercase tracking-wider">AM Out</th>
                      <th class="text-center px-3 py-2 text-white/40 uppercase tracking-wider">PM In</th>
                      <th class="text-center px-3 py-2 text-white/40 uppercase tracking-wider">PM Out</th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-white/5">
                    @forelse($row['daily_logs'] as $day)
                      <tr class="{{ $day['is_late'] ? 'bg-red-500/5' : '' }}">
                        <td class="px-3 py-2 text-white/70">{{ $day['date'] }}</td>
                        <td class="px-3 py-2 text-center {{ $day['is_late'] ? 'text-red-400 font-semibold' : 'text-white' }}">
                          {{ $day['morning_in'] }}
                        </td>
                        <td class="px-3 py-2 text-center text-white/60">{{ $day['morning_out'] }}</td>
                        <td class="px-3 py-2 text-center text-white">{{ $day['afternoon_in'] }}</td>
                        <td class="px-3 py-2 text-center text-white/60">{{ $day['afternoon_out'] }}</td>
                      </tr>
                    @empty
                      <tr>
                        <td colspan="5" class="px-3 py-4 text-center text-white/30">No scan records this month.</td>
                      </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </td>
          </tr>
        @empty
          <tr>
            <td colspan="11" class="px-6 py-12 text-center text-white/30 text-sm">
              No employee data found for this period.
            </td>
          </tr>
        @endforelse
      </tbody>
    </table>
  </div>
</div>
@endsection
